## 🧮 Ejercicios de NumPy 🧮


1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [7]:
list = [27, 5, 34, 2, 4, 1, 94, 75, 67, 58]

array1 = np.array(list)

array1

array([27,  5, 34,  2,  4,  1, 94, 75, 67, 58])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [9]:
empty_array = np.empty_like(array1, dtype = object)

In [10]:
counter = 0 

for element in array1:
    if element % 2 == 0:
        empty_array[counter] = 'par'
        counter +=1
    else:
        empty_array[counter] = 'impar'
        counter +=1

empty_array


array(['impar', 'impar', 'par', 'par', 'par', 'impar', 'par', 'impar',
       'impar', 'par'], dtype=object)

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [12]:
array2 = np.reshape(empty_array, (2,5))
array2

array([['impar', 'impar', 'par', 'par', 'par'],
       ['impar', 'par', 'impar', 'impar', 'par']], dtype=object)

5. Extrae los elementos comunes de los siguientes arrays




In [15]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [16]:
np.intersect1d(array1, array2)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2

In [17]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales

In [18]:
np.intersect1d(array1, array2, return_indices=True)

(array([2, 4]), array([1, 5]), array([1, 5]))

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. 

In [21]:
array_integer = np.random.randint(0, 50 ,(3,5))
array_integer

array([[20, 11, 48, 31, 44],
       [12, 31, 49, 33,  4],
       [12, 13, 10, 31, 39]])

> Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [24]:
array_integer = [(array_integer < 10) | (array_integer) > 40]

array_integer

[array([[False, False,  True, False,  True],
        [False, False,  True, False, False],
        [False, False, False, False, False]])]

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [25]:
array_float = np.random.uniform(low=5, high= 10, size= (5,3)).round(2)
array_float

array([[6.94, 6.87, 7.39],
       [7.41, 8.12, 8.68],
       [6.61, 7.8 , 7.53],
       [6.03, 5.75, 9.2 ],
       [7.17, 7.16, 8.81]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

In [26]:
array_3d = np.random.randint(1, 20, (2, 4, 7))
array_3d

array([[[14, 18,  1, 17, 12, 10,  8],
        [ 5,  8,  5, 11, 11,  6,  2],
        [18,  9, 14, 16, 11, 15, 19],
        [10,  4, 12,  9, 15,  7, 19]],

       [[ 9, 13,  6, 18, 15, 18,  5],
        [ 9, 19, 19,  5,  9,  5,  9],
        [19,  2,  2,  7,  7, 11,  3],
        [17,  5,  8, 12,  8, 19, 19]]])

> Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas


In [27]:
array_3d_transposed = np.transpose (array_3d, (1, 2, 0))
array_3d_transposed

array([[[14,  9],
        [18, 13],
        [ 1,  6],
        [17, 18],
        [12, 15],
        [10, 18],
        [ 8,  5]],

       [[ 5,  9],
        [ 8, 19],
        [ 5, 19],
        [11,  5],
        [11,  9],
        [ 6,  5],
        [ 2,  9]],

       [[18, 19],
        [ 9,  2],
        [14,  2],
        [16,  7],
        [11,  7],
        [15, 11],
        [19,  3]],

       [[10, 17],
        [ 4,  5],
        [12,  8],
        [ 9, 12],
        [15,  8],
        [ 7, 19],
        [19, 19]]])